In [15]:
#张量创建与基础运算
import torch
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
print(x.shape)

torch.Size([12])


In [18]:
X = x.reshape(3,4)
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [19]:
print(torch.zeros(2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [20]:
print(torch.ones(2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [21]:
print(torch.randn(3,4))


tensor([[-1.4616, -0.7795, -0.2843,  0.9042],
        [-0.5358,  2.7391, -0.5415,  0.7226],
        [-0.0173,  0.9350, -0.8252,  0.2263]])


In [22]:
print(torch.tensor([[2,1,4],[5,4,5]]))

tensor([[2, 1, 4],
        [5, 4, 5]])


In [26]:
#张量计算
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**y)
print(torch.exp(x))

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1.,  4., 16., 64.])
tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


In [39]:
print(X.sum())


tensor(66.)


In [42]:
#广播机制
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)
print(a)
print(b)
print(a+b)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [45]:
#内存与原地操作
befor = id(Y)
Y+=X
print(id(Y)==befor)


True


In [46]:
befor = id(Y)
Y=X+Y
print(id(Y)==befor)

False


In [48]:
#转换为其他python对象,相互转换
A = X.numpy()
B = torch.tensor(A)
print(type(A),type(B))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
